install:
	sudo apt-get install python3-pip
        sudo pip3 install flask
	sudo pip3 install feedparser

	sudo apt-get install python-dev
	sudo apt-get install libxml2-dev libxslt-dev
	sudo apt-get install libjpeg-dev zlib1g-dev libpng12-dev

	sudo pip3 install newspaper3k
	curl https://raw.githubusercontent.com/codelucas/newspaper/master/download_corpora.py | python3

run:
	python run.py
